api_get:
    path: /api/post
    controller: App\Controller\ApiController::getAll
    methods: get

api_post:
    path: /api/post
    controller: App\Controller\ApiController::create
    methods: put
