<?php

declare(strict_types=1);

namespace App\Tests\Application\Domain;

use App\Application\Domain\CreatePost;
use App\Application\Domain\PostBodyValidator;
use App\Application\Infrastructure\PostRepositoryInterface;
use App\Entity\User;
use PHPUnit\Framework\TestCase;

class CreatePostTest extends TestCase
{
    private CreatePost $createPost;
    private PostBodyValidator $postBodyValidator;
    private PostRepositoryInterface $postRepository;
    private string $body = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.';

    public function setUp(): void
    {
        $this->postRepository = $this->createMock(PostRepositoryInterface::class);
        $this->postBodyValidator = $this->createMock(PostBodyValidator::class);
        $this->createPost = new CreatePost($this->postRepository, $this->postBodyValidator);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    final public function testExecute(): void
    {
        $author = new User();

        $this->postBodyValidator->expects($this->once())
            ->method('execute')
            ->with($this->body)
            ->willReturn($this->body);

        $this->postRepository->expects($this->once())->method('save');

        $post = $this->createPost->execute($author, 'Test title', $this->body);
        $this->assertStringContainsString('Test title', $post->getTitle());
        $this->assertStringContainsString($this->body, $post->getBody());
        $this->assertEquals($author, $post->getAuthor());
    }
}
